name: analyze

on:
  workflow_call:
    inputs:
      php:
        default: '8.3'
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --no-interaction --no-progress --no-scripts

      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format=github
