name: deploy

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1
        with:
          trigger_url: ${{ inputs.url }}
