name: deploy

on:
  workflow_call:
    secrets:
      TRIGGER_URL:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          trigger_url: ${{ secrets.TRIGGER_URL }}
