name: lint

on:
  workflow_call:
    inputs:
      php:
        default: '8.3'
        type: string
      message:
        default: (ignore) Apply style fixes
        type: string
      fix:
        default: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "$GH_ACTIONS_NAME"
          git config user.email "$GH_ACTIONS_EMAIL"
        env:
          GH_ACTIONS_NAME: ${{ vars.GH_ACTIONS_NAME }}
          GH_ACTIONS_EMAIL: ${{ vars.GH_ACTIONS_EMAIL }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit changes
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}
          commit_user_name: $GH_ACTIONS_NAME
          commit_user_email: $GH_ACTIONS_EMAIL
          commit_author: $GH_ACTIONS_NAME <${GH_ACTIONS_EMAIL}>
        env:
          GH_ACTIONS_NAME: ${{ vars.GH_ACTIONS_NAME }}
          GH_ACTIONS_EMAIL: ${{ vars.GH_ACTIONS_EMAIL }}
