name: sync

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Configure Git
        run: |
          git config fetch.prune true
          git config pull.rebase true
          git config rebase.autoStash true
          git config user.name "${{ vars.GH_ACTIONS_NAME }}"
          git config user.email "${{ vars.GH_ACTIONS_EMAIL }}"

      - name: Check branch
        id: check-branch
        run: |
          git fetch origin

          if [ -z "$(git ls-remote --heads origin development)" ]; then
            echo "in-sync=true" >> $GITHUB_OUTPUT
          else
            mainAhead=$(git rev-list --left-right --count origin/main...origin/development | awk '{print $1}')
            developmentAhead=$(git rev-list --left-right --count origin/main...origin/development | awk '{print $2}')

            if [ "$mainAhead" -eq 0 ] && [ "$developmentAhead" -eq 0 ]; then
              echo "in-sync=true" >> $GITHUB_OUTPUT
            else
              echo "in-sync=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Sync branch
        if: steps.check-branch.outputs.in-sync == 'false'
        run: |
          git checkout development
          git pull origin development
          git rebase origin/main
          git push --force-with-lease origin development
